- name: build solana
  become: true
  become_user: solana
  shell: ". \"$HOME/.cargo/env\" && CI_COMMIT=$(git rev-parse HEAD) scripts/cargo-install-all.sh /mnt/operational/solana/{{ repo_version }}"
  args:
    chdir: "/mnt/operational/solana/{{ repo_dir }}"
    executable: /bin/bash
