- name: download latest snapshot
  become: true
  become_user: solana
  shell: python3 {{ path_to_project }}/snapshot-finder.py --snapshot_path {{ path_to_project }}/snapshots --rpc_address {{ rpc_address }} &>>{{ path_to_project }}/logs/snapshot_download.log
