- name: setup solana-validator.service
  become: true
  become_user: root
  copy:
    src: solana-validator.service
    dest: /etc/systemd/system/solana-validator.service
    owner: root
    group: root
    mode: "0755"

- name: copy restart.sh
  become: true
  become_user: solana
  copy:
    src: restart.sh
    dest: {{ path_to_project }}/restart.sh
    owner: solana
    group: solana
    mode: "0755"
    
- name: copy download_start.sh
  become: true
  become_user: solana
  copy:
    src: download_start.sh
    dest: {{ path_to_project }}/download_start.sh
    owner: solana
    group: solana
    mode: "0755"

- name: copy snapcheck.py
  become: true
  become_user: solana
  copy:
    src: snapcheck.py
    dest: {{ path_to_project }}/snapcheck.py
    owner: solana
    group: solana

- name: copy snapshot-finder.py
  become: true
  become_user: solana
  copy:
    src: snapshot-finder.py
    dest: {{ path_to_project }}/snapshot-finder.py
    owner: solana
    group: solana

- name: copy montip.py
  become: true
  become_user: solana
  copy:
    src: montip.py
    dest: {{ path_to_project }}/montip.py
    owner: solana
    group: solana
