- name: Set sysctl performance variables
  become: true
  become_user: root
  shell:
    # Note: this overwrite the file, if you want to append replace EOM with EOF
    cmd: |
      sudo bash -c "cat >/etc/sysctl.d/21-agave-validator.conf <<EOF
      # Increase max UDP buffer sizes
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728

      # Increase memory mapped files limit
      vm.max_map_count = 1000000

      # Increase number of allowed open file descriptors
      fs.nr_open = 1000000
      EOF"
  args:
    executable: /bin/bash

- name: Reload sysctl
  become: true
  become_user: root
  shell: 
    cmd: |
      sysctl -p /etc/sysctl.d/21-agave-validator.conf
  args:
    executable: /bin/bash